// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.views'], ['zz.tests.models.SimplestDataset', 'zz.views.Base'], false);
goog.addDependency('/../../../../../../../lib/sources/enums/basecss.js', ['zz.views.enums.BaseCss'], [], false);
goog.addDependency('/../../../../../../../lib/sources/views/base.js', ['zz.views.Base'], ['goog.dom', 'goog.ui.Component.State', 'goog.ui.Control', 'zz.models.IModelSubscriber', 'zz.models.Message', 'zz.models.enums.EventType', 'zz.views.BaseRenderer'], false);
goog.addDependency('/../../../../../../../lib/sources/views/baserenderer.js', ['zz.views.BaseRenderer'], ['goog.ui.ControlRenderer', 'zz.views.enums.BaseCss'], false);
goog.addDependency('/../../../../../../../lib/sources/views/baseview.js', ['zz.views.BaseView'], ['goog.dom', 'goog.json', 'goog.ui.Component', 'zz.models.IModelSubscriber', 'zz.models.Message', 'zz.models.enums.EventType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/base.js', ['zz.models', 'zz.models.Message'], ['goog.async.run', 'zz.models.enums.EventType', 'zz.models.events.DatarowUpdate'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/enums/errortype.js', ['zz.models.enums.ErrorType'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/enums/eventtype.js', ['zz.models.enums.EventType'], ['goog.events'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/enums/fieldtypes.js', ['zz.models.enums.FieldType'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/events/datarowcreate.js', ['zz.models.events.DatarowCreate'], ['zz.events.BaseEvent', 'zz.models.enums.EventType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/events/datarowdelete.js', ['zz.models.events.DatarowDelete'], ['zz.events.BaseEvent', 'zz.models.enums.EventType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/events/datarowupdate.js', ['zz.models.events.DatarowUpdate'], ['zz.events.BaseEvent', 'zz.models.enums.EventType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/models/datarow.js', ['zz.models.Datarow'], ['goog.object', 'zz.models', 'zz.models.enums.ErrorType', 'zz.models.enums.FieldType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/models/dataset.js', ['zz.models.Dataset'], ['goog.array', 'goog.async.run', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.object', 'goog.pubsub.PubSub', 'zz.models', 'zz.models.Message', 'zz.models.enums.ErrorType', 'zz.models.enums.EventType', 'zz.models.events.DatarowCreate', 'zz.models.events.DatarowDelete'], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/lib/sources/models/imodelsubscriber.js', ['zz.models.IModelSubscriber'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/node_modules/zz.events/lib/sources/base.js', ['zz.events'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.models/node_modules/zz.events/lib/sources/events/baseevents.js', ['zz.events.BaseEvent'], ['goog.events.Event'], false);
goog.addDependency('/../../../../../../../node_modules/zz.tests/lib/sources/base.js', ['zz.tests'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.tests/lib/sources/models/simplest.js', ['zz.tests.models.SimplestDatarow', 'zz.tests.models.SimplestDataset'], ['zz.models.Datarow', 'zz.models.Dataset', 'zz.models.enums.FieldType'], false);
